version: "3"

services:
  app:
    build: .
    container_name: "store_backend"
    depends_on:
      - db
    environment:
      - JDBC_DATABASE_URL=jdbc:postgresql://db:5432/store
      - JDBC_DATABASE_USERNAME=postgres
      - JDBC_DATABASE_PASSWORD=password
    ports:
      - "8080:8080"

  db:
    image: "postgres:latest"
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./src/main/resources/scripts/initTables.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: "store_db"