DROP TABLE IF EXISTS
    CATEGORY,
    ARTPIECE,
    IMAGE,
    ARTORDER,
    ORDERITEM;

CREATE TABLE CATEGORY (
ID SERIAL NOT NULL,
CATEGORY_NAME TEXT NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE ARTPIECE (
ID SERIAL NOT NULL,
NAME text NOT NULL,
PRICE REAL NOT NULL,
DESCRIPTION TEXT NOT NULL,
CATEGORY_ID int NOT NULL,
PRIMARY KEY(ID),
CONSTRAINT fk_category
FOREIGN KEY(CATEGORY_ID)
REFERENCES CATEGORY(ID)
);

CREATE TABLE IMAGE (
ID SERIAL NOT NULL,
LINK TEXT NOT NULL,
ARTPIECE_ID INT NOT NULL,
PRIMARY KEY(ID),
CONSTRAINT fk_artpiece
FOREIGN KEY(ARTPIECE_ID)
REFERENCES ARTPIECE(ID)
);

CREATE TABLE ARTORDER (
ID SERIAL NOT NULL,
TOTAL REAL NOT NULL,
CUSTOMER_EMAIL TEXT NOT NULL,
ORDERED_AT_TIMESTAMP BIGINT NOT NULL,
FULLFILLED boolean NOT NULL,
PRIMARY KEY(ID)
);

CREATE TABLE ORDERITEM (
ID SERIAL NOT NULL,
AMOUNT INT NOT NULL,
ORDER_ID INT NOT NULL,
ITEM_ID INT NOT NULL,
PRIMARY KEY(ID),
CONSTRAINT fk_order
FOREIGN KEY(ORDER_ID)
REFERENCES ARTORDER(ID),
CONSTRAINT fk_item
FOREIGN KEY(ITEM_ID)
REFERENCES ARTPIECE(ID)
);
