CREATE TABLE CATEGORY (
CATEGORY_ID SERIAL NOT NULL,
CATEGORY_NAME TEXT NOT NULL,
PRIMARY KEY(CATEGORY_ID)
);

CREATE TABLE ARTPIECE (
ARTPIECE_ID SERIAL NOT NULL,
NAME text NOT NULL,
PRICE REAL NOT NULL,
DESCRIPTION TEXT NOT NULL,
CATEGORY_ID int NOT NULL,
PRIMARY KEY(ARTPIECE_ID),
CONSTRAINT fk_category
FOREIGN KEY(CATEGORY_ID)
REFERENCES CATEGORY(CATEGORY_ID)
);

CREATE TABLE IMAGE (
IMAGE_ID SERIAL NOT NULL,
LINK TEXT NOT NULL,
ARTPIECE_ID INT NOT NULL,
PRIMARY KEY(IMAGE_ID),
CONSTRAINT fk_artpiece
FOREIGN KEY(ARTPIECE_ID)
REFERENCES ARTPIECE(ARTPIECE_ID)
);

CREATE TABLE ARTORDER (
ORDER_ID SERIAL NOT NULL,
TOTAL REAL NOT NULL,
CUSTOMER_EMAIL TEXT NOT NULL,
ORDERED_AT_TIMESTAMP BIGINT NOT NULL,
FULLFILLED boolean NOT NULL,
PRIMARY KEY(ORDER_ID)
);

CREATE TABLE ORDERITEM (
ORDERITEM_ID SERIAL NOT NULL,
AMOUNT INT NOT NULL,
ORDER_ID INT NOT NULL,
ITEM_ID INT NOT NULL,
PRIMARY KEY(ORDERITEM_ID),
CONSTRAINT fk_order
FOREIGN KEY(ORDER_ID)
REFERENCES ARTORDER(ORDER_ID),
CONSTRAINT fk_item
FOREIGN KEY(ITEM_ID)
REFERENCES ARTPIECE(ARTPIECE_ID)
);
