version: "3"
services:
  database:
    image: "postgres:latest"
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./initTables.sql:/docker-entrypoint-initdb.d/init.sql
    container_name: "pg_store"